### ISSUE TITLE
compute 6D rotation representation from rotation matrix or quaternion

### ISSUE THREAD

**Issue by kaixin-bai** [Janus-Shiau/6d_rot_tensorflow#1]
Thanks a lot for your code.
Do you know how to compute 6D rotation representation from rotation matrix or quaternion?

**Comment by Janus-Shiau** [comment]
Hi @kaixin-bai,

Thank you for your interesting.

For your question, to be brief, directly concatenating the vector of X and Y axis is the proposed idea in the papers. That is, for a tensor `mat` with shape [...,3,3], its 6D rotation representation `r6d` will be `r6d = tf.concat([mat[...,0], mat[...,1]], axis=-1)`. FYI, I also update the code with a function `tf_matrix_to_rotation6d`.

Besides, the details can be found in the case 3 of Section 4.2 and Appendix B in the paper.
